name: Node Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install packages
        run: npm install

      - name: start server and test API
        run: |
          node server.js &
          sleep 5
          curl http://localhost:5000
