name : Node CICD

on:
    push:

jobs:
    build:
     runs-on : ubuntu-latest

     steps:
       - name : install Vm 
         uses : actions/checkout@v4
     
       - name : install node
         uses : actions/setup-node@v4
         with:
             node-version : 22
         
       - name : install dependiencies
         run : npm install

       - name : start servet and test API 
         run :  |
             node server.js &
             sleep 5
             curl http://localhost:5000
    
